name: Validate LightPlacer jsons

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Validate json
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: https://raw.githubusercontent.com/FlayaN/LightPlacer-VR/refs/heads/json-schema/schema.json
          file: package/**/LightPlacer/**/*.json
      
      - name: Download release archive
        uses: robinraju/release-downloader@v1
        with:
          repository: 'Mutagen-Modding/Spriggit'
          latest: true
          zipBall: true
          fileName: 'SpriggitLinuxCLI.zip'
          out-file-path: './downloads'
      
      - name: Clear tmp
        run: rm -rf /tmp/Spriggit

      - name: Extract archive
        run: unzip ./downloads/SpriggitLinuxCLI.zip -d ./SpriggitCLI

      - name: Prepare dist directory
        run: |
          if [ -d "dist" ]; then
            rm -rf dist
          else
            mkdir dist
          fi

      - name: Copy package to dist excluding files
        run: |
          mkdir -p dist
          rsync -av --exclude-from='exclusions.txt' package/ dist/

      - name: Set permissions for Spriggit executable
        run: chmod +x ./SpriggitCLI/Spriggit.CLI

      - name: List directory contents for debugging
        run: |
          echo "Contents of ./SpriggitCLI:"
          ls -l ./SpriggitCLI
          echo "Contents of current directory:"
          pwd
          ls -l

      - name: Run Spriggit deserialization
        run: |
          ./SpriggitCLI/Spriggit.CLI deserialize -i "./Spriggit/PL - Bright" -o "./dist/PL - Bright.esp"
        continue-on-error: true
         
      - name: List directory contents for debugging
        run: |
          echo "Contents of /tmp/Spriggit:"
          ls -lR /tmp/Spriggit


