name: Validate Placed Light

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Validate json
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: https://raw.githubusercontent.com/FlayaN/LightPlacer-VR/refs/heads/json-schema/schema.json
          file: package/**/LightPlacer/**/*.json
      
      - name: Download release archive
        uses: robinraju/release-downloader@v1
        with:
          repository: 'Mutagen-Modding/Spriggit'
          latest: true
          zipBall: true
          fileName: 'SpriggitCLI.zip'
          out-file-path: './downloads'
      
      - name: Extract archive
        run: unzip ./downloads/SpriggitCLI.zip -d ./SpriggitCLI
      
      - name: Run Spriggit main deserialization
        run: ./deserialize.bat
        shell: cmd

