name: Validate LightPlacer jsons

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{ github.head_ref }}

      - name: Validate json
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: https://raw.githubusercontent.com/FlayaN/LightPlacer-VR/refs/heads/json-schema/schema.json
          file: package/**/LightPlacer/**/*.json
      
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Download release archive
        uses: robinraju/release-downloader@v1
        with:
          repository: 'Mutagen-Modding/Spriggit'
          latest: true
          zipBall: true
          fileName: 'SpriggitLinuxCLI.zip'
          out-file-path: './SpriggitCLI'
      
      - name: Extract archive
        run: unzip ./SpriggitCLI/SpriggitLinuxCLI.zip -d ./SpriggitCLI

      - name: Prepare dist directory
        run: |
          if [ -d "dist" ]; then
            rm -rf dist
          else
            mkdir dist
          fi

      - name: Copy package to dist excluding files
        run: |
          mkdir -p dist
          rsync -av --exclude-from='exclusions.txt' package/ dist/

      - name: Set permissions for Spriggit executable
        run: chmod +x ./SpriggitCLI/Spriggit.CLI

      - name: Run Spriggit deserialization
        run: |
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/PL - Bright" -o "dist/PL - Bright.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/PL - Nightmare" -o "dist/PL - Nightmare.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/PL - Dark" -o "dist/PL - Dark.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/PL - Default" -o "dist/PL - Default.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/Placed Light - Spots" -o "dist/Placed Light - Spots.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/Placed Light Exteriors" -o "dist/Placed Light Exteriors.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/Placed Light" -o "dist/Placed Light.esm"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/Placed Light - Shadows and Ambient" -o "dist/Placed Light - Shadows and Ambient.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/Misc Patches/NOTWL - Lanterns" -o "dist/Misc Patches/NOTWL - Lanterns.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/Misc Patches/Placed Light - CC" -o "dist/Misc Patches/Placed Light - CC.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/Misc Patches/Placed Light Exteriors - NOTWL 3 patch" -o "dist/Misc Patches/Placed Light Exteriors - NOTWL 3 patch.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/Misc Patches/Carbon LightBulbs Edit" -o "dist/Misc Patches/Carbon LightBulbs Edit.esp"
          ./SpriggitCLI/Spriggit.CLI deserialize -i "Spriggit/Misc Patches/Placed Light - Creation Club" -o "dist/Misc Patches/Placed Light - Creation Club.esp"
